### ISSUE TITLE
Difusión de nuestra investigación sobre Desaparecidos en la Democracia Argentina

### ISSUE THREAD

**Issue by cancerbero-arg** [mnofresno/estadisticas#1]
Sentite libre de borrar este issue, solo buscamos divulgar nuestra investigación.
https://cancerbero-arg.github.io/desaparecidos-en-democracia-argentina/

**Comment by mnofresno** [comment]
Gracias @cancerbero-arg por tu mensaje.
Me parece muy bueno lo que hicieron ustedes. Acá estamos recién comenzando con éste proyecto. Si quieren podemos seguir en contacto por e-mail, fb o slack. Saludos!
